# Generated by Django 3.2.9 on 2021-11-12 14:41

from django.db import migrations
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0007_alter_genericpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='image_slideshow',
            field=wagtail.core.fields.StreamField([('image_1', wagtail.images.blocks.ImageChooserBlock()), ('image_2', wagtail.images.blocks.ImageChooserBlock()), ('image_3', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
    ]
